[connections.postgresql]
dialect = "postgresql"
host = "c7u1tn6bvvsodf.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com"
port = "5432"
database = "d5pimsiqoh7def"
username = "ubmu6d2s07pnqn"
password = "p9ebd6be1654f81c53355ab325234dbdcded4ba73bc1fe1de1eb62aa979257b6e"
